### ISSUE TITLE
--password password.txt not working

### ISSUE THREAD

**Issue by ymister587** [elkokc/roundcubebruter#1]
Hello.
I'm trying to do the command --password password.txt (to use a file)
but it doesn't work. and looking at the code I can't find how to do it.
Thank you for your help.

**Comment by elkokc** [comment]
Hi sir,
When brute forcing a mail service, it's rather about a password spraying. So initially I didn't implement support of a passwords list. 
But sure it can be customized. We could iterate trough the passwords list with a delay.
